
(()=>{
const $=s=>document.querySelector(s), viewport=$('#viewport'),paper=$('#paper'),workspace=$('#workspace'),comment=$('#comment');
let meta={};try{meta=JSON.parse($('#va-meta').textContent)}catch{};
$('#artifactTitle').textContent=meta.title||'Untitled diagram';document.title=`${meta.title||'Visual Architect'} — Review Studio`;$('#typeChip').textContent=meta.type||'Diagram';$('#revisionChip').textContent=meta.revision||'r1';$('#statusChip').textContent=meta.status||'Ready';
const storageKey=`visual-architect:review:${meta.title||location.pathname}`;let feedback=[];try{feedback=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{};
let current={id:'diagram',label:'Whole diagram',kind:'general'},scale=1,tx=0,ty=0,drag=false,lastX=0,lastY=0,toastTimer;
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1300)}
function persist(){localStorage.setItem(storageKey,JSON.stringify(feedback))}
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('visual-architect:theme',t)}
const preferred=localStorage.getItem('visual-architect:theme')||(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark');setTheme(preferred);
$('#themeBtn').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function apply(){paper.style.transform=`translate(-50%,-50%) translate(${tx}px,${ty}px) scale(${scale})`;$('#zoomValue').textContent=`${Math.round(scale*100)}%`}
function fit(){const pw=1200,ph=760,pad=52;scale=Math.min((viewport.clientWidth-pad)/pw,(viewport.clientHeight-pad)/ph,1.15);scale=Math.max(.28,scale);tx=0;ty=0;apply()}
function zoom(delta){scale=Math.max(.28,Math.min(2.4,scale+delta));apply()}
$('#zoomIn').onclick=()=>zoom(.12);$('#zoomOut').onclick=()=>zoom(-.12);$('#fit').onclick=fit;window.addEventListener('resize',()=>{if(innerWidth<560&&scale<.3)fit()});requestAnimationFrame(fit);
function selectElement(el){document.querySelectorAll('.va-selected').forEach(x=>x.classList.remove('va-selected'));if(el){el.classList.add('va-selected');current={id:el.dataset.vaId,label:el.dataset.vaLabel||el.dataset.vaId,kind:el.dataset.vaKind||'element'};$('#selectionPill').classList.add('show');$('#selectionPillLabel').textContent=current.label;$('#selectionPillId').textContent=current.id}else{current={id:'diagram',label:'Whole diagram',kind:'general'};$('#selectionPill').classList.remove('show')}$('#selectedLabel').textContent=current.label;$('#selectedId').textContent=current.id;$('#selectedKind').textContent=current.kind}
viewport.addEventListener('click',e=>{const el=e.target.closest('[data-va-id]');if(el){e.stopPropagation();selectElement(el)}});$('#generalBtn').onclick=()=>{selectElement(null);comment.focus()};
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('[data-va-id]')||e.button!==0)return;drag=true;lastX=e.clientX;lastY=e.clientY;paper.classList.add('dragging');viewport.setPointerCapture(e.pointerId)});viewport.addEventListener('pointermove',e=>{if(!drag)return;tx+=e.clientX-lastX;ty+=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;apply()});viewport.addEventListener('pointerup',()=>{drag=false;paper.classList.remove('dragging')});viewport.addEventListener('pointercancel',()=>{drag=false;paper.classList.remove('dragging')});viewport.addEventListener('wheel',e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();zoom(e.deltaY<0?.08:-.08)},{passive:false});
document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{comment.value=(comment.value?comment.value+'\n':'')+b.dataset.quick;comment.focus()});
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){const open=feedback.filter(x=>x.status!=='resolved').length;$('#reviewCount').textContent=`${open} open`;const list=$('#feedbackList');if(!feedback.length){list.className='empty';list.textContent='No feedback yet. Click a diagram element to start.';return}list.className='';list.innerHTML=feedback.map((f,i)=>`<article class="review-item ${f.status==='resolved'?'resolved':''}"><div class="review-top"><span class="status">${f.status==='resolved'?'Resolved':'Open'}</span><b title="${esc(f.elementId)}">${esc(f.elementLabel)}</b></div><div class="review-text">${esc(f.comment)}</div><div class="review-time">${new Date(f.createdAt).toLocaleString()} · ${esc(f.elementId)}</div><div class="item-actions"><button class="tinybtn" data-resolve="${i}" title="${f.status==='resolved'?'Reopen':'Resolve'}">${f.status==='resolved'?'↺':'✓'}</button><button class="tinybtn" data-delete="${i}" title="Delete">×</button></div></article>`).join('');list.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>{const f=feedback[+b.dataset.resolve];f.status=f.status==='resolved'?'open':'resolved';persist();render()});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{feedback.splice(+b.dataset.delete,1);persist();render()})}
$('#addFeedback').onclick=()=>{const text=comment.value.trim();if(!text){toast('Write feedback first');return}feedback.push({elementId:current.id,elementLabel:current.label,elementKind:current.kind,comment:text,status:'open',revision:meta.revision||'r1',createdAt:new Date().toISOString()});comment.value='';persist();render();toast('Feedback added')};
$('#clearResolved').onclick=()=>{feedback=feedback.filter(x=>x.status!=='resolved');persist();render();toast('Resolved feedback cleared')};
function reviewJson(){return JSON.stringify({schema:'visual-architect/review@1',artifact:{title:meta.title||document.title,type:meta.type||null,revision:meta.revision||null},summary:{open:feedback.filter(x=>x.status!=='resolved').length,resolved:feedback.filter(x=>x.status==='resolved').length},feedback},null,2)}
async function copyText(t){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.append(a);a.select();document.execCommand('copy');a.remove()}}
$('#copyJson').onclick=async()=>{await copyText(reviewJson());toast('Review JSON copied')};$('#downloadJson').onclick=()=>{const blob=new Blob([reviewJson()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='visual-architect-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Review JSON downloaded')};
$('#togglePanel').onclick=()=>workspace.classList.toggle('panel-hidden');document.addEventListener('keydown',e=>{if(e.target.matches('textarea,input'))return;if(e.key==='Escape')selectElement(null);if(e.key==='0'){e.preventDefault();fit()}if(e.key==='+'||e.key==='=')zoom(.12);if(e.key==='-')zoom(-.12);if(e.key.toLowerCase()==='r')workspace.classList.toggle('panel-hidden')});
selectElement(null);render();
})();
